//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustWorkshopUploader.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RustWorkshopUploader.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We are creating and selling private plugins. Do you want to check our website?.
        /// </summary>
        internal static string AdvMessage {
            get {
                return ResourceManager.GetString("AdvMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profitable proposition.
        /// </summary>
        internal static string AdvMessage_Title {
            get {
                return ResourceManager.GetString("AdvMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application error: {0}.
        /// </summary>
        internal static string AppError {
            get {
                return ResourceManager.GetString("AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE.
        /// </summary>
        internal static string BtnDo_Update {
            get {
                return ResourceManager.GetString("BtnDo_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPLOAD.
        /// </summary>
        internal static string BtnDo_Upload {
            get {
                return ResourceManager.GetString("BtnDo_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPLOADING....
        /// </summary>
        internal static string BtnDo_Uploading {
            get {
                return ResourceManager.GetString("BtnDo_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to Deserialize file {0} as CustomSkin!
        ///{1}.
        /// </summary>
        internal static string CustomSkin_DeserializationFailed {
            get {
                return ResourceManager.GetString("CustomSkin_DeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You should set the description!.
        /// </summary>
        internal static string Do_NoDescription {
            get {
                return ResourceManager.GetString("Do_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You should chose image file!.
        /// </summary>
        internal static string Do_NoImage {
            get {
                return ResourceManager.GetString("Do_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You should set item name!.
        /// </summary>
        internal static string Do_NoName {
            get {
                return ResourceManager.GetString("Do_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: {0}.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR.
        /// </summary>
        internal static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SUCCESS.
        /// </summary>
        internal static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to accept Steam Subscriber Agreement, would you like to do it now?.
        /// </summary>
        internal static string NeedsWorkshopAgreement {
            get {
                return ResourceManager.GetString("NeedsWorkshopAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entry upload complete!
        ///Open workshop page?.
        /// </summary>
        internal static string Publish_OpenBrowser {
            get {
                return ResourceManager.GetString("Publish_OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retrieve information from Steam .
        /// </summary>
        internal static string Publish_RetreiveFailed {
            get {
                return ResourceManager.GetString("Publish_RetreiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to open selected file.
        /// </summary>
        internal static string Select_UnableToOpen {
            get {
                return ResourceManager.GetString("Select_UnableToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image resolutions should be 512x512!.
        /// </summary>
        internal static string Select_WrongResolution {
            get {
                return ResourceManager.GetString("Select_WrongResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam is not running!.
        /// </summary>
        internal static string SteamNotFound {
            get {
                return ResourceManager.GetString("SteamNotFound", resourceCulture);
            }
        }
    }
}
